apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: drf9vixuz-go 
  janus-idp.io/tekton: drf9vixuz-go
  backstage.io/kubernetes-id: drf9vixuz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: drf9vixuz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml